theme: jekyll-theme-minimal
title: [Intro to Metrics]
description: [An Course taught by Professor Zhaopeng Qu,Business School,NJU]
logo: [https://github.com/MetricsNJU/Metrics_2018/blob/master/Pics/ashenfelter.jpg]
show_downloads: ["true"]
google_analytics: [UA-123672411-1]