title: [Intro to 'Metrics]
description: [Course taught by Professor Zhaopeng Qu at Business School of NJU]
logo: /Pics/ashenfelter.jpg
show_downloads: true 
google_analytics: UA-123672411-1
theme: jekyll-theme-minimal